Feature/update schema
fingerprintjs/fingerprint-pro-server-api-java-sdk pull request #51
Opened 2024-07-31 15:00 UTC by sshelomentsev

2024-07-31 15:18 UTC, ilfa requested changes
1. `update SDK according to new schema` not an informative message for release notes, we need to mention all the changes
2. We need to add tests and examples for new methods: `delete_visitor_data` and `update_event`

2024-07-31 15:18 UTC, ilfa commented on scripts/generate.sh
> +sed -i '' -e "s/projectVersion = .*$/projectVersion = $VERSION/g" ./gradle.properties
You just broke it for linux, try to check the platform like [here](https://github.com/fingerprintjs/fingerprint-pro-server-api-python-sdk/blob/main/generate.sh#L47)

2024-07-31 15:18 UTC, ilfa commented on scripts/sync.sh
>  )
Looks like you need to add new examples for new methods

2024-07-31 15:18 UTC, ilfa commented on sdk/src/main/java/com/fingerprint/api/FingerprintApi.java
> +  public void updateEvent(String requestId, EventUpdateRequest eventUpdateRequest) throws ApiException {
We need to add tests for this method

2024-08-06 11:23 UTC, ilfa approved these changes

2024-08-06 11:25 UTC, ilfa approved these changes

2024-08-07 08:22 UTC, Orkuncakilkaya approved these changes

2024-08-07 09:23 UTC, merged