chore: fix broken example link
fingerprintjs/fingerprint-pro-server-api-java-sdk pull request #87
Opened 2024-11-21 16:02 UTC by JuroUhlar

2024-11-21 16:35 UTC, necipallef submitted a review, later dismissed

2024-11-21 17:03 UTC, ilfa approved these changes

2024-11-21 17:03 UTC, ilfa requested changes
You need to fix template and generate a readme from it

2024-11-25 11:24 UTC, Orkuncakilkaya approved these changes

2024-11-25 11:25 UTC, ilfa approved these changes

2024-11-25 11:25 UTC, merged